plugins {
    id 'fabric-loom' version '1.15-SNAPSHOT'
}

// These lines make the mod filename `{mod.id}-${mod.version}+${sc.current.version}.jar`
version = "${property('mod.version')}+${sc.current.version}"
base.archivesName = property('mod.id') as String

loom {
    splitEnvironmentSourceSets()

    mods {
        "winter-of-making" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }

}

repositories {
    maven { url = "https://maven.shedaniel.me" }
}

fabricApi {
    configureDataGeneration {
        client = true
    }
}


def requiredJava = JavaVersion.VERSION_21

dependencies {
    minecraft "com.mojang:minecraft:${sc.current.version}"
    mappings "net.fabricmc:yarn:${property('deps.yarn_mappings')}:v2"

    modImplementation "net.fabricmc:fabric-loader:${property('deps.fabric_loader')}"
    modImplementation("net.fabricmc.fabric-api:fabric-api:${property("deps.fabric_api")}")

    modCompileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:${property("deps.rei")}"
    modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:${property("deps.rei")}"
}


java {
    withSourcesJar()
    sourceCompatibility = requiredJava
    targetCompatibility = requiredJava
}

processResources {
    inputs.property("minecraft_version", sc.current.version)
    inputs.property("version", version)
    filesMatching("fabric.mod.json") {
        expand([
                "minecraft_version": sc.current.version,
                "version"          : version
        ])
    }
}