# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G -XX:+UseZGC -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=4

# Mod Properties
mod.version=1.0.1
maven_group=singh.akaalroop.winter_of_making
mod.id=winter-of-making
# Stonecutter
dev.kikugie.stonecutter.hard_mode=true