pluginManagement {
    def isCI = System.getenv("CI") != null
    repositories {
        gradlePluginPortal()
        if (!isCI) {
            maven {
                name = 'Fabric'
                url = uri("http://raspberrypi.local:8080/Fabric")
                allowInsecureProtocol = true
            }
            maven {
                name = "MavenCentral"
                url = uri("http://raspberrypi.local:8080/Maven-Central")
                allowInsecureProtocol = true
            }
            maven {
                name = "piREI"
                url = uri("http://raspberrypi.local:8080/REI")
                allowInsecureProtocol = true
            }
        }
        maven {
            url = "https://maven.kikugie.dev/snapshots"
            name = "KikuGie Snapshots"
        }
    }
}

plugins {
    id("dev.kikugie.stonecutter").version "0.9"
}

dependencyResolutionManagement {
    def isCI = System.getenv("CI") != null
    repositories {
        if (!isCI) {
            maven {
                name = "piMavenCentral"
                url = uri("http://raspberrypi.local:8080/Maven-Central")
                allowInsecureProtocol = true
            }
            maven {
                name = "piFabric"
                url = uri("http://raspberrypi.local:8080/Fabric")
                allowInsecureProtocol = true
            }
            maven {
                name = "piREI"
                url = uri("http://raspberrypi.local:8080/REI")
                allowInsecureProtocol = true
            }
        }
    }
}

stonecutter {
    kotlinController = false
    centralScript = "build.gradle"

    // Configuration goes here
    create(getRootProject()) {
        versions "1.20", "1.20.1", "1.21", "1.21.1", "1.21.2", "1.21.3", "1.21.4", "1.21.5", "1.21.6", "1.21.7", "1.21.8", "1.21.9", "1.21.10", "1.21.11"
        vcsVersion = "1.21.8"
    }
}